#!/usr/bin/env python3
"""
Extract katakana glyphs from Misaki 8x8 font (column-major, SSD1306-ready).

Source: 8x8DotJPFont / misaki_font_f0.h
Original: http://littlelimit.net/misaki.htm (Num Kadoma, free use)
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
F0_PATH = ROOT / "tools" / "misaki_font_f0.h"
OUT_PATH = ROOT / "firmware" / "pcb_quest" / "kana_glyphs.h"

KANA = (
    "アイウエオ"
    "カキクケコ"
    "サシスセソ"
    "タチツテト"
    "ナニヌネノ"
    "ハヒフヘホ"
    "マミムメモ"
    "ヤユヨ"
    "ラリルレロ"
    "ワヲン"
)

DRUM_EXTRA = (
    "ガギグゲゴ"
    "ザジズゼゾ"
    "ダヂヅデド"
    "バビブベボ"
    "パピプペポ"
    "0123456789"
)

DRUM_CHARS = KANA + DRUM_EXTRA

# misaki_font_f0 index for each drum character
MISAKI_F0_INDEX = {
    "ア": 0x97, "イ": 0x99, "ウ": 0x9B, "エ": 0x9D, "オ": 0x9F,
    "カ": 0xA0, "キ": 0xA2, "ク": 0xA4, "ケ": 0xA6, "コ": 0xA8,
    "ガ": 0xA1, "ギ": 0xA3, "グ": 0xA5, "ゲ": 0xA7, "ゴ": 0xA9,
    "サ": 0xAA, "シ": 0xAC, "ス": 0xAE, "セ": 0xB0, "ソ": 0xB2,
    "ザ": 0xAB, "ジ": 0xAD, "ズ": 0xAF, "ゼ": 0xB1, "ゾ": 0xB3,
    "タ": 0xB4, "チ": 0xB6, "ツ": 0xB9, "テ": 0xBB, "ト": 0xBD,
    "ダ": 0xB5, "ヂ": 0xB7, "ヅ": 0xBA, "デ": 0xBC, "ド": 0xBE,
    "ナ": 0xBF, "ニ": 0xC0, "ヌ": 0xC1, "ネ": 0xC2, "ノ": 0xC3,
    "ハ": 0xC4, "ヒ": 0xC7, "フ": 0xCA, "ヘ": 0xCD, "ホ": 0xD0,
    "バ": 0xC5, "ビ": 0xC8, "ブ": 0xCB, "ベ": 0xCE, "ボ": 0xD1,
    "パ": 0xC6, "ピ": 0xC9, "プ": 0xCC, "ペ": 0xCF, "ポ": 0xD2,
    "マ": 0xD3, "ミ": 0xD4, "ム": 0xD5, "メ": 0xD6, "モ": 0xD7,
    "ヤ": 0xD9, "ユ": 0xDB, "ヨ": 0xDD,
    "ラ": 0xDE, "リ": 0xDF, "ル": 0xE0, "レ": 0xE1, "ロ": 0xE2,
    "ワ": 0xE4, "ヲ": 0xE7, "ン": 0xE8,
    "0": 0x39, "1": 0x3A, "2": 0x3B, "3": 0x3C, "4": 0x3D,
    "5": 0x3E, "6": 0x3F, "7": 0x40, "8": 0x41, "9": 0x42,
    "?": 0x08,   # ？
}


NAME_MAP = {
    "ア": "A", "イ": "I", "ウ": "U", "エ": "E", "オ": "O",
    "カ": "KA", "キ": "KI", "ク": "KU", "ケ": "KE", "コ": "KO",
    "サ": "SA", "シ": "SHI", "ス": "SU", "セ": "SE", "ソ": "SO",
    "タ": "TA", "チ": "CHI", "ツ": "TSU", "テ": "TE", "ト": "TO",
    "ナ": "NA", "ニ": "NI", "ヌ": "NU", "ネ": "NE", "ノ": "NO",
    "ハ": "HA", "ヒ": "HI", "フ": "FU", "ヘ": "HE", "ホ": "HO",
    "マ": "MA", "ミ": "MI", "ム": "MU", "メ": "ME", "モ": "MO",
    "ヤ": "YA", "ユ": "YU", "ヨ": "YO",
    "ラ": "RA", "リ": "RI", "ル": "RU", "レ": "RE", "ロ": "RO",
    "ワ": "WA", "ヲ": "WO", "ン": "N",
    "ガ": "GA", "ギ": "GI", "グ": "GU", "ゲ": "GE", "ゴ": "GO",
    "ザ": "ZA", "ジ": "JI", "ズ": "ZU", "ゼ": "ZE", "ゾ": "ZO",
    "ダ": "DA", "ヂ": "DI", "ヅ": "DU", "デ": "DE", "ド": "DO",
    "バ": "BA", "ビ": "BI", "ブ": "BU", "ベ": "BE", "ボ": "BO",
    "パ": "PA", "ピ": "PI", "プ": "PU", "ペ": "PE", "ポ": "PO",
    "0": "D0", "1": "D1", "2": "D2", "3": "D3", "4": "D4",
    "5": "D5", "6": "D6", "7": "D7", "8": "D8", "9": "D9",
}


def glyph_const_name(ch: str) -> str:
    return f"GLYPH_{NAME_MAP[ch]}"


def parse_f0(path: Path) -> list[list[int]]:
    text = path.read_text(encoding="utf-8")
    glyphs: list[list[int]] = []
    for m in re.finditer(
        r"\{\s*((?:0x[0-9A-Fa-f]{2}\s*,\s*){7}0x[0-9A-Fa-f]{2})\s*\}", text
    ):
        nums = [int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]{2}", m.group(1))]
        glyphs.append(nums)
    if len(glyphs) < 0xEF:
        raise RuntimeError(f"Expected >= 0xEF glyphs, got {len(glyphs)}")
    return glyphs


def glyph_row_visual(cols: list[int]) -> list[str]:
    lines = []
    for row in range(8):
        line = ""
        for col in range(8):
            bit = 1 << row
            line += "#" if cols[col] & bit else "."
        lines.append(line)
    return lines


def emit(glyphs_f0: list[list[int]]) -> str:
    kana_count = len(DRUM_CHARS)
    lines = [
        "// Auto-generated by tools/gen_kana_glyphs.py",
        "// Glyphs from Misaki 8x8 font (http://littlelimit.net/misaki.htm)",
        "// via 8x8DotJPFont (emutyworks). Free to use/redistribute.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"#define KANA_COUNT {kana_count}",
        "#define KANA_DRUM_LEN KANA_COUNT",
        "#define GLYPH_BYTES 8",
        "",
        "// Drum order:",
        "// アイウエオ カキクケコ サシスセソ タチツテト ナニヌネノ",
        "// ハヒフヘホ マミムメモ ヤユヨ ラリルレロ ワヲン",
        "// ガギグゲゴ ザジズゼゾ ダヂヅデド バビブベボ パピプペポ",
        "// 0123456789",
        "",
        "enum GlyphId : uint8_t {",
    ]

    for i, ch in enumerate(DRUM_CHARS):
        lines.append(f"  {glyph_const_name(ch)} = {i},")

    lines.extend([
        "  GLYPH_QUESTION = KANA_COUNT,",
        "};",
        "",
        "// Column-major page bytes (Misaki / SSD1306 native layout).",
        "static const uint8_t KANA_GLYPHS[][GLYPH_BYTES] PROGMEM = {",
    ])

    def append_glyph(label: str, cols: list[int]) -> None:
        row = ", ".join(f"0x{b:02X}" for b in cols)
        lines.append(f"  // {label}")
        lines.append(f"  {{ {row} }},")

    for ch in DRUM_CHARS:
        idx = MISAKI_F0_INDEX[ch]
        append_glyph(ch, glyphs_f0[idx])

    append_glyph("?", glyphs_f0[MISAKI_F0_INDEX["?"]])

    lines.append("};")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    if not F0_PATH.exists():
        raise SystemExit(
            f"Missing {F0_PATH}. Copy from 8x8DotJPFont/JPLang8x8Text/misaki_font_f0.h"
        )

    glyphs_f0 = parse_f0(F0_PATH)

    # Sanity check: ア and ナ must differ
    a = glyphs_f0[MISAKI_F0_INDEX["ア"]]
    i = glyphs_f0[MISAKI_F0_INDEX["イ"]]
    na = glyphs_f0[MISAKI_F0_INDEX["ナ"]]
    if a == i or a == na or i == na:
        raise RuntimeError("Glyph sanity check failed: ア/イ/ナ are not distinct")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(emit(glyphs_f0), encoding="utf-8")
    print(f"Wrote {OUT_PATH}")

    # Preview key glyphs
    for ch in ("ア", "イ", "ナ", "シ"):
        cols = glyphs_f0[MISAKI_F0_INDEX[ch]]
        print(f"\n=== {ch} ===")
        for line in glyph_row_visual(cols):
            print(line)


if __name__ == "__main__":
    main()
